version: '3'
services:
  springboot-app:
    ports:
      - 8080:8080
    build:
      context: .
      args:
        JAR_FILE: /springboot-cassandra.jar
    depends_on:
      - "cassandra-seed"
    environment:
      REPLICATION_FACTOR: 3
    restart: always

  cassandra-seed:
    image: cassandra
    ports:
      - "9042:9042"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=banksMarketingCampaign"
      - "CASSANDRA_DC=datacenter"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"

  cassandra-node1:
    image: cassandra
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=banksMarketingCampaign"
      - "CASSANDRA_DC=datacenter"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    depends_on:
      - "cassandra-seed"

  cassandra-node2:
    image: cassandra
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 60 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=banksMarketingCampaign"
      - "CASSANDRA_DC=datacenter"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    depends_on:
      - "cassandra-seed"